@host = https://localhost:7219

@filter = Fish

GET {{host}}/api/products
GET {{host}}/api/products/1
GET {{host}}/api/products?filter={{filter}}
PUT {{host}}/api/products/1
Content-Type: application/json

{
	"Id": 1,
	"Name":"My",
	"Description": "Lorem ipsum",
	"Price": 0
}